name: VMC CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v1
        
      - name: Prepare Env
        run: dotnet tool install --global dotnet-sonarscanner --version 4.8.0
        
      - name: Anayze
        run: |
            dotnet sonarscanner begin /k:"kotauchisunsun_VirtualMotionCapture"
            dotnet build ControlWindowWPF\ControlWindowWPF.sln
            dotnet sonarscanner end 
