name: VMC CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v1
        
      - name: Prepare Env
        run: |
          choco install  -y wget unzip
          wget "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.7.1.2311/sonar-scanner-msbuild-4.7.1.2311-net46.zip"
          unzip sonar-scanner-msbuild-4.7.1.2311-net46.zip
        
      - name: Anayze
        run: |
            Set-Item Env:Path "$Env:Path;$Pwd\sonar-scanner-4.1.0.1829\bin\;"
            sonar-scanner --help
            sonar-scanner begin \
              -D "sonar.projectKey=kotauchisunsun_VirtualMotionCapture" \
              -D "sonar.organization=kotauchisunsun-github" \
              -D "sonar.host.url=https://sonarcloud.io" \
              -D "sonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}"
            &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"  ControlWindowWPF\ControlWindowWPF.sln
            sonar-scanner end \
              -D "sonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}"
