name: VMC CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v1
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
