name: VMC CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v1
      
      - name: check
        run:  |
          "${env:ProgramFiles(x86)}"'\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' /?
        
      - name: Prepare Env
        run: dotnet tool install --global dotnet-sonarscanner --version 4.8.0
        
      - name: Anayze
        run: |
            dotnet sonarscanner begin /k:"kotauchisunsun_VirtualMotionCapture" /o:"kotauchisunsun-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}"
            ${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ControlWindowWPF\ControlWindowWPF.sln
            dotnet sonarscanner end /d:"sonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}"
