name: VMC CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v1
        
      - name: Test MSBuild.exe
        run: MSBuild.exe
